import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  groundSchoolPPLSidebar: [{type: 'autogenerated', dirName: 'groundSchoolPPL'}],
  phakSidebar: [{type: 'autogenerated', dirName: 'phak'}],
  //   phakSidebar: [
  //   'phak/intro', // maps to docs/phak/intro.md
  //   {
  //     type: 'category',
  //     label: 'Section A',
  //     items: [
  //       // 'phak/section-a/topic1', // docs/phak/section-a/topic1.md
  //       // 'phak/section-a/topic2'
  //     ]
  //   },
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

if (process.env.NODE_ENV === 'development') {
  sidebars['localOnly'] = [{type: 'autogenerated', dirName: 'local'}]
}

export default sidebars;
