name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  testbuilddeploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Step 5: Fail the build if tests fail
      - name: Verify test results
        if: failure()
        run: echo "Tests failed. Build failed."

      - name: build the app
        run: npm run build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   if: success()

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Apply the Template
        run: |
          cd terraform
          terraform init -input=false
          terraform plan -input=false
          terraform apply -auto-approve

      - name: sync build files
        run: |
          ls -al
          cd build
          ls -al
          aws s3 sync . s3://skybound-dev --exclude "*.DS_Store"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
